### ISSUE TITLE
Does it have any storage limits with this adaptor?

### ISSUE THREAD

**Issue by aprihodko** [stockulus/pouchdb-react-native#15]
PouchDB docs suggest using the WebSQL adaptor as it limited only by a free space. Does AsyncStorage have any limitations?

**Comment by stockulus** [comment]
Hi,

The AsynStorage stores the data in 
https://facebook.github.io/react-native/docs/asyncstorage.html
I do not know any Limits, but currently the adapter uses a Leveldown wrapper, and not AsyncStorage directly. The Leveldown wrapper stores all Keys in memory, so I would not recommend to store > 10000 Docs, because of memory. I currently working on avoiding to use the Leveldown bridge, and write a more direct adapter; just need to find the time. And in the End it is still a Phone your app is running on.
