### ISSUE TITLE
Cannot run Jest unit tests due to import statements

### ISSUE THREAD

**Issue by dikarel** [stockulus/pouchdb-react-native#46]
This library does not seem to play well with [Jest](https://facebook.github.io/jest/), which is what Facebook recommends for unit-testing React Native projects. I believe this is due to this library's usage of `import` statements.

Any chance the `import` statements could be transpiled away before being published to npm?

**Repro script**

```bash
npm install -g react-native-cli@latest
react-native init testproject
cd testproject
npm install pouchdb-react-native
echo "import PouchDB from 'pouchdb-react-native'" >> __tests__/index.android.js
npm test
```

**npm test output**

![screen shot 2016-11-25 at 11 44 08 pm](https://cloud.githubusercontent.com/assets/15131271/20631456/2c78a682-b369-11e6-8f0a-0580d7214f93.png)

**Comment by ewnd9** [comment]
This is correct, problem in es6 code in `node_modules`

You can modify the `jest` property in `package.json` in order to transpile `pouchdb-react-native`

```json
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|pouchdb-react-native|pouchdb-adapter-asyncstorage)"
    ]
  },
```

See more at:

https://facebook.github.io/jest/docs/tutorial-react-native.html#transformignorepatterns-customization
https://github.com/facebook/jest/blob/master/packages/jest-react-native/jest-preset.json#L18-L20
